# Generated by Django 4.2.16 on 2024-11-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('wishlist', '0002_alter_wishlist_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='user_profile',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='customer_wishlist', to='profiles.userprofile'),
        ),
    ]
